name: ft-ls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: leaks
      run: valgrind ./ft_ls -r -R -a -t -l test src -t Makefile -x
